"""Is the L enhancement of S(q) a quantum effect or an ice-rule effect?

The claim in the paper is that the large equal-time structure factor at
L, which drives the Feynman ratio down, is generated by the quantum
ring dynamics and is not already present in the classical ice ensemble.
That claim needs a controlled comparison, with error bars.

Two independent controls are computed here.

(1) EXACT, same cluster, no statistics required.  The Rokhsar-Kivelson
    equal-amplitude state on the ground-state winding sector of the
    very same 48-site cluster is a classical ice ensemble restricted to
    exactly the configurations the quantum state can reach.  Its S(q)
    is an exact sum over 9104 configurations, so there is no sampling
    error at all, and it isolates the effect of the AMPLITUDES: same
    configurations, same cluster, uniform weights instead of the
    interacting ground-state weights.

(2) THERMODYNAMIC, with error bars.  Loop-update Monte Carlo on a
    2048-site classical ice manifold, binned so that the reported
    S(q) carries a standard error.  This checks that the near-flatness
    is not itself a finite-size artifact of the 48-site cluster.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
from scipy.sparse.linalg import eigsh

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "notes"))
sys.path.insert(0, str(ROOT / "campaign"))

import recompute_finite_size_artifact as geometry               # noqa: E402
from run_momentum_resolved_spectrum import star                 # noqa: E402
from run_ring48_dssf import contractible                        # noqa: E402
from ring48_momenta_fix import fcc_momenta                      # noqa: E402
from ring64_pipeline import (fast_labels, fast_ring,            # noqa: E402
                             hex_masks_patterns)
import roton_bz_dispersion as cls                               # noqa: E402

OUT = ROOT / "campaign" / "outputs" / "ring_model_dssf"
NBIN = 30
NPER = 60
NLOOP = 40


def log(m, t0):
    print(f"[{time.perf_counter()-t0:7.1f}s] {m}", flush=True)


def main() -> int:
    t0 = time.perf_counter()
    rec = {}

    # ---------- (1) exact equal-amplitude comparison ------------------
    cl = geometry.build_cluster("fcc", (2, 2, 3))
    n = int(cl.n_sites)
    states = np.sort(np.asarray(cl.ice_states, dtype=np.uint64))
    positions = np.asarray(cl.positions, dtype=float)
    labels, spins_all = fast_labels(states, positions)
    hmp = hex_masks_patterns(contractible(cl))
    ham, _ = fast_ring(states, hmp, 0.0)
    _, v0 = eigsh(ham, k=1, which="SA", tol=1e-11, ncv=80)
    occ = {int(s): float(np.sum(v0[labels == s, 0] ** 2))
           for s in np.unique(labels)}
    sector = max(occ, key=occ.get)
    rows = np.where(labels == sector)[0]
    spins = spins_all[rows]
    gs = np.asarray(v0[rows, 0], dtype=float)
    gs /= np.linalg.norm(gs)
    flat = np.ones(len(rows)) / np.sqrt(len(rows))
    log(f"48-site sector {sector}: {len(rows)} configurations", t0)

    sub = np.arange(n) % 4
    momenta, _ = fcc_momenta(cl)
    tab = []
    for q in momenta:
        phase = np.exp(-2j * np.pi * (positions @ q))
        sq = {}
        for name, amp in (("quantum", gs), ("equal_amplitude", flat)):
            tot = 0.0
            for mu in range(4):
                col = (spins @ (phase * (sub == mu)))
                tot += float(np.sum(amp ** 2 * np.abs(col) ** 2))
            sq[name] = tot / n
        tab.append({"q": [float(x) for x in q], "star": star(q), **sq})
        log(f"  {star(q):<20s} S_quantum = {sq['quantum']:.5f}   "
            f"S_equal_amp = {sq['equal_amplitude']:.5f}   "
            f"ratio {sq['quantum']/max(sq['equal_amplitude'],1e-30):.3f}", t0)
    rec["exact_same_cluster"] = tab

    qs = {r["star"]: r for r in tab}
    if "L" in qs:
        lq, lc = qs["L"]["quantum"], qs["L"]["equal_amplitude"]
        others_q = [r["quantum"] for r in tab
                    if r["star"] not in ("L", "Gamma") and r["quantum"] > 1e-9]
        others_c = [r["equal_amplitude"] for r in tab
                    if r["star"] not in ("L", "Gamma")
                    and r["equal_amplitude"] > 1e-9]
        log(f"\n  L enhancement over other momenta:", t0)
        log(f"    quantum ground state : {lq:.5f} vs mean "
            f"{np.mean(others_q):.5f}  -> {lq/np.mean(others_q):.3f}x", t0)
        log(f"    equal-amplitude state: {lc:.5f} vs mean "
            f"{np.mean(others_c):.5f}  -> "
            f"{lc/np.mean(others_c):.3f}x", t0)
        rec["L_enhancement_quantum"] = float(lq / np.mean(others_q))
        rec["L_enhancement_equal_amp"] = float(lc / np.mean(others_c))

    # ---------- (2) 2048-site classical MC with error bars ------------
    rng = np.random.default_rng(20260821)
    pos, csub, tetA, tetB, cells, cidx = cls.build(cls.LBOX)
    nsite = len(pos)
    ta, tb = cls.site_tetra(tetA, tetB, nsite)
    sigma = cls.seed_ice(csub)
    da, db = cls.ice_defects(sigma, tetA, tetB)
    log(f"\nclassical L={cls.LBOX}: {nsite} sites, ice defects "
        f"A={da} B={db}", t0)
    if da or db:
        log("  seeding failed -- classical control skipped", t0)
    else:
        for _ in range(cls.NSWEEP_EQ):
            cls.loop_update(sigma, tetA, tetB, ta, tb, rng)
        da, db = cls.ice_defects(sigma, tetA, tetB)
        log(f"  equilibrated, ice defects A={da} B={db}", t0)
        qlist = [("Gamma", [0, 0, 0]), ("L", [0.5, 0.5, 0.5]),
                 ("X", [1.0, 0.0, 0.0]), ("W", [1.0, 0.5, 0.0]),
                 ("K", [0.75, 0.75, 0.0])]
        qarr = np.array([q for _, q in qlist], dtype=float)
        phase = np.exp(-2j * np.pi * (qarr @ pos.T))
        masks = [csub == mu for mu in range(4)]
        bins = np.zeros((NBIN, len(qlist)))
        for b in range(NBIN):
            acc = np.zeros(len(qlist))
            for _ in range(NPER):
                for _ in range(NLOOP):
                    cls.loop_update(sigma, tetA, tetB, ta, tb, rng)
                s = sigma.astype(float) * 0.5
                for mk in masks:
                    acc += np.abs(phase[:, mk] @ s[mk]) ** 2
            bins[b] = acc / (NPER * nsite)
            if (b + 1) % 10 == 0:
                log(f"  bin {b+1}/{NBIN}", t0)
        mean = bins.mean(axis=0)
        err = bins.std(axis=0, ddof=1) / np.sqrt(NBIN)
        log("\n  classical S(q), 2048 sites, "
            f"{NBIN} bins x {NPER} measurements:", t0)
        out = []
        for i, (name, q) in enumerate(qlist):
            log(f"    {name:<6s} {mean[i]:.5f} +/- {err[i]:.5f}", t0)
            out.append({"label": name, "q": q, "S": float(mean[i]),
                        "err": float(err[i])})
        rec["classical_2048"] = out
        nong = [i for i, (nm, _) in enumerate(qlist) if nm != "Gamma"]
        sp = (mean[nong].max() - mean[nong].min())
        log(f"    spread across non-Gamma momenta: {sp:.5f}  "
            f"(typical error {err[nong].mean():.5f})", t0)
        rec["classical_spread"] = float(sp)
        rec["classical_typ_err"] = float(err[nong].mean())

    with open(OUT / "classical_comparison.json", "w") as fh:
        json.dump(rec, fh, indent=1, default=float)
    log("wrote classical_comparison.json", t0)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
